<?php

namespace Gore\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * KeywordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KeywordRepository extends EntityRepository
{
        
    /**
     * getAllCategories
     * Return all the categories on the blog
     * @return type
     */
    public function getAllCategories(){
        return $this->getAllKeywords(true);
    }
    
    
    
    /**
     * getAllKeywords
     * Get all keywords in database
     * @param type $category
     * @return type
     */
    public function getAllKeywords($category = false){
        $qb = $this->createQueryBuilder('k')
                   ->where('k.category = :categoryparam')
                   ->setParameter('categoryparam', $category)
                   ->orderBy('k.name', 'ASC');
        
        return $qb->getQuery()->getResult();
    }
    
    
    
    /**
     * getMostUsedKeywords
     * Get most used keywords on the blog
     * @param type $numberOfKeywords
     * @param type $includeCategories
     * @return type
     */
    public function getMostUsedKeywords($numberOfKeywords, $includeCategories = false){
        $qb = $this->createQueryBuilder('k')
                   ->select('k.id, k.name, count(k) as compteur')
                   ->join('k.articles', 'a')
                   ->groupBy('k.id, k.name')
                   ->orderBy('compteur', 'DESC')
                   ->setFirstResult(0)
                   ->setMaxResults($numberOfKeywords);
        
        if (!$includeCategories) $qb->where('k.category = false');
        
        return $qb->getQuery()->getResult();
    }

    
    
    /**
     * getKeywordIfExists
     * Check if a keyword exists in DB
     * NOTE : the Keyword in parameter is not a DB Keyword but a Keyword
     * created by the form->bind() ; id doesn't have any ID yet
     * @param \Gore\BlogBundle\Entity\Keyword $keyword
     * @return null if there is 0 et many keywords with this name ; the 
     * keyword if it's alone in the DB
     */
    public function getKeywordIfExists(Keyword $keyword){
         $qb = $this->createQueryBuilder('k')
                    ->where('k.category = false')
                    ->where('k.name = :name')
                    ->setParameter('name', $keyword->getName());
         
         return $qb->getQuery()->getOneOrNullResult();
    }
}
